### ISSUE TITLE
incomplete turning of character when turning multiple times

### ISSUE THREAD

**Issue by PLATnya** [AureliusVarro/SoG_Test_Task#8]
when player press button for turning character few times in short time chartacter rotates through an incomplete angle.
Just make tag for turning ability and add this tag in blocked tags in this ability.

**Comment by AureliusVarro** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Multiple turns possibility](https://trello.com/c/R88eKCyh/20-multiple-turns-possibility)

**Comment by AureliusVarro** [comment]
Fixed
